name: Build and Deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master


          sudo chown $( whoami ):$( whoami ) ${{ github.workspace }}/_site
          "



    - name: vuepress-deploy
      uses: jenkey2011/vuepress-deploy@master
      env:
        ACCESS_TOKEN: ${{ secrets.DEPLOY }}
        TARGET_REPO: OCR4all/OCR4all.github.io
        TARGET_BRANCH: gh-pages
        BUILD_SCRIPT: yarn add yarn-build
        BUILD_DIR: sudo chown $( whoami ):$( whoami ) ${{ github.workspace }}/docs/.vuepress/dist/
              run: |
                    cd ${{ github.workspace }}/_site
                    git init -b gh-pages
                    git config user.name ${{ github.actor }}
                    git config user.email ${{ github.actor }}@users.noreply.github.com
                    git remote add origin https://x-access-token:${{ github.token }}@github.com/${{ github.repository }}.git
                    git add .
                    git commit -m "Deploy site built from commit ${{ github.sha }}
                    git push -f -u origin gh-pages
